server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /v1/ {
    proxy_pass http://openconfer-server:8787;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /v1/join/ {
    access_log off;
    proxy_pass http://openconfer-server:8787;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /join/ {
    access_log off;
    try_files $uri /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
